parameters:
    database_host: mysql-ornythorink.alwaysdata.net
    database_port: null
    database_name: ornythorink_shoes
    database_user: 142339_test
    database_password: boheme80
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 0344fa93aa4579f274fc54a2c5f02c50f33b9fb2